import { DomainValidationError } from '../../shared/domain/errors';

/**
 * Downloads the export behind an Open Helpdesk export link (POST /workspaces/:slug/export/token
 * hands out `${API_URL}/workspaces/<slug>/export/<token>`, served by the public
 * GET /workspaces/:slug/export/:token). Only URLs of that shape are fetched, so an import cannot be
 * pointed at arbitrary endpoints. An optional /api prefix covers servers behind a reverse proxy.
 */
export const EXPORT_LINK_PATH = /^(?:\/api)?\/workspaces\/[a-z0-9-]+\/export\/[A-Za-z0-9_-]+$/;

export const EXPORT_LINK_MAX_BYTES = 100 * 1024 * 1024;
export const EXPORT_LINK_TIMEOUT_MS = 30_000;

export const MSG_NOT_AN_EXPORT_LINK = 'Only export links generated by Open Helpdesk can be imported';
export const MSG_EXPORT_TOO_LARGE = 'The export is too large';

export type FetchLike = (url: string, init: RequestInit) => Promise<Response>;

export interface ExportLinkDownloadOptions {
  fetchImpl?: FetchLike;
  timeoutMs?: number;
  maxBytes?: number;
}

export function parseExportLink(raw: string): URL {
  let url: URL;
  try {
    url = new URL(raw);
  } catch {
    throw new DomainValidationError(MSG_NOT_AN_EXPORT_LINK);
  }
  if (url.protocol !== 'http:' && url.protocol !== 'https:') throw new DomainValidationError(MSG_NOT_AN_EXPORT_LINK);
  if (url.username || url.password) throw new DomainValidationError(MSG_NOT_AN_EXPORT_LINK);
  if (!EXPORT_LINK_PATH.test(url.pathname)) throw new DomainValidationError(MSG_NOT_AN_EXPORT_LINK);
  return url;
}

export async function downloadExportLink(raw: string, options: ExportLinkDownloadOptions = {}): Promise<Buffer> {
  const url = parseExportLink(raw);
  const fetchImpl: FetchLike = options.fetchImpl ?? ((u, init) => fetch(u, init));
  const maxBytes = options.maxBytes ?? EXPORT_LINK_MAX_BYTES;
  const controller = new AbortController();
  let timedOut = false;
  const timer = setTimeout(() => {
    timedOut = true;
    controller.abort();
  }, options.timeoutMs ?? EXPORT_LINK_TIMEOUT_MS);

  try {
    let response: Response;
    try {
      response = await fetchImpl(url.toString(), { redirect: 'manual', signal: controller.signal });
    } catch {
      throw new DomainValidationError(
        timedOut ? 'Timed out downloading the export' : 'Could not reach the export link',
      );
    }

    if (response.status >= 300 && response.status < 400) {
      throw new DomainValidationError('The export link redirects elsewhere; only direct export links can be imported');
    }
    if (!response.ok) {
      const hint = response.status === 401 || response.status === 404
        ? ': the link is invalid, expired or was already used'
        : '';
      throw new DomainValidationError(`Could not download the export (HTTP ${response.status})${hint}`);
    }
    const declared = Number(response.headers.get('content-length'));
    if (Number.isFinite(declared) && declared > maxBytes) {
      controller.abort();
      throw new DomainValidationError(MSG_EXPORT_TOO_LARGE);
    }
    if (!response.body) return Buffer.alloc(0);

    const reader = response.body.getReader();
    const chunks: Uint8Array[] = [];
    let total = 0;
    for (;;) {
      let next: ReadableStreamReadResult<Uint8Array>;
      try {
        next = await reader.read();
      } catch {
        throw new DomainValidationError(
          timedOut ? 'Timed out downloading the export' : 'The export download was interrupted',
        );
      }
      if (next.done) break;
      total += next.value.byteLength;
      if (total > maxBytes) {
        controller.abort();
        await reader.cancel().catch(() => undefined);
        throw new DomainValidationError(MSG_EXPORT_TOO_LARGE);
      }
      chunks.push(next.value);
    }
    return Buffer.concat(chunks);
  } finally {
    clearTimeout(timer);
  }
}

/**
 * Export links are single use, so the bytes a preview downloaded are kept for the import that
 * follows it (and for a retry after a wrong password), one download per workspace and user.
 */
const RECENT_TTL_MS = 30 * 60 * 1000;
const recent = new Map<string, { url: string; bytes: Buffer; expiresAt: number }>();

export function recallExportDownload(key: string, url: string): Buffer | null {
  const now = Date.now();
  for (const [k, entry] of recent) if (entry.expiresAt < now) recent.delete(k);
  const entry = recent.get(key);
  return entry && entry.url === url ? entry.bytes : null;
}

export function rememberExportDownload(key: string, url: string, bytes: Buffer): void {
  recent.set(key, { url, bytes, expiresAt: Date.now() + RECENT_TTL_MS });
}

export function forgetExportDownload(key: string): void {
  recent.delete(key);
}
