import { createWriteStream } from 'node:fs';
import { unlink } from 'node:fs/promises';
import { once } from 'node:events';
import { finished } from 'node:stream/promises';
import { DomainValidationError } from '../../shared/domain/errors';

/**
 * Downloads the export behind an Open Helpdesk export link (POST /workspaces/:slug/export/token
 * hands out `${API_URL}/workspaces/<slug>/export/<token>`, served by the public
 * GET /workspaces/:slug/export/:token). Only URLs of that shape are fetched, so an import cannot be
 * pointed at arbitrary endpoints. An optional /api prefix covers servers behind a reverse proxy.
 */
export const EXPORT_LINK_PATH = /^(?:\/api)?\/workspaces\/[a-z0-9-]+\/export\/[A-Za-z0-9_-]+$/;

/** Default ceiling on the downloaded file; the controller passes WORKSPACE_IMPORT_MAX_MB. */
export const EXPORT_LINK_MAX_BYTES = 2048 * 1024 * 1024;
/** No response, or no bytes, for this long aborts the download. */
export const EXPORT_LINK_IDLE_TIMEOUT_MS = 30_000;
/** Ceiling on the whole download (WORKSPACE_IMPORT_URL_TIMEOUT_SECONDS, default 600). */
export const EXPORT_LINK_TIMEOUT_MS = 10 * 60_000;

export const MSG_NOT_AN_EXPORT_LINK = 'Only export links generated by Open Helpdesk can be imported';
export const MSG_EXPORT_TOO_LARGE = 'The export is too large';

export type FetchLike = (url: string, init: RequestInit) => Promise<Response>;

export interface ExportLinkDownloadOptions {
  fetchImpl?: FetchLike;
  /** Total time allowed for the download. */
  timeoutMs?: number;
  /** Time allowed without a response or without new bytes. */
  idleTimeoutMs?: number;
  maxBytes?: number;
}

export function exportLinkTimeoutFromEnv(): number {
  const seconds = Number(process.env.WORKSPACE_IMPORT_URL_TIMEOUT_SECONDS);
  return Number.isFinite(seconds) && seconds > 0 ? seconds * 1000 : EXPORT_LINK_TIMEOUT_MS;
}

export function parseExportLink(raw: string): URL {
  let url: URL;
  try {
    url = new URL(raw);
  } catch {
    throw new DomainValidationError(MSG_NOT_AN_EXPORT_LINK);
  }
  if (url.protocol !== 'http:' && url.protocol !== 'https:') throw new DomainValidationError(MSG_NOT_AN_EXPORT_LINK);
  if (url.username || url.password) throw new DomainValidationError(MSG_NOT_AN_EXPORT_LINK);
  if (!EXPORT_LINK_PATH.test(url.pathname)) throw new DomainValidationError(MSG_NOT_AN_EXPORT_LINK);
  return url;
}

/**
 * Downloads an export link into `filePath` (created, never overwritten) without holding the body
 * in memory, and returns its size. On any failure the partial file is removed.
 */
export async function downloadExportLink(
  raw: string,
  filePath: string,
  options: ExportLinkDownloadOptions = {},
): Promise<number> {
  const url = parseExportLink(raw);
  const fetchImpl: FetchLike = options.fetchImpl ?? ((u, init) => fetch(u, init));
  const maxBytes = options.maxBytes ?? EXPORT_LINK_MAX_BYTES;
  const idleTimeoutMs = options.idleTimeoutMs ?? EXPORT_LINK_IDLE_TIMEOUT_MS;
  const controller = new AbortController();
  let timedOut = false;
  const abortForTime = () => {
    timedOut = true;
    controller.abort();
  };
  const total = setTimeout(abortForTime, options.timeoutMs ?? EXPORT_LINK_TIMEOUT_MS);
  let idle = setTimeout(abortForTime, idleTimeoutMs);
  const stillAlive = () => {
    clearTimeout(idle);
    idle = setTimeout(abortForTime, idleTimeoutMs);
  };
  const timeoutError = () => new DomainValidationError('Timed out downloading the export');

  let out: ReturnType<typeof createWriteStream> | null = null;
  try {
    let response: Response;
    try {
      response = await fetchImpl(url.toString(), { redirect: 'manual', signal: controller.signal });
    } catch {
      throw timedOut ? timeoutError() : new DomainValidationError('Could not reach the export link');
    }
    stillAlive();

    if (response.status >= 300 && response.status < 400) {
      throw new DomainValidationError('The export link redirects elsewhere; only direct export links can be imported');
    }
    if (!response.ok) {
      const hint = response.status === 401 || response.status === 404
        ? ': the link is invalid, expired or was already used'
        : '';
      throw new DomainValidationError(`Could not download the export (HTTP ${response.status})${hint}`);
    }
    const declared = Number(response.headers.get('content-length'));
    if (Number.isFinite(declared) && declared > maxBytes) {
      controller.abort();
      throw new DomainValidationError(MSG_EXPORT_TOO_LARGE);
    }

    const file = createWriteStream(filePath, { flags: 'wx' });
    out = file;
    let size = 0;
    if (response.body) {
      const reader = response.body.getReader();
      for (;;) {
        let next: ReadableStreamReadResult<Uint8Array>;
        try {
          next = await reader.read();
        } catch {
          throw timedOut ? timeoutError() : new DomainValidationError('The export download was interrupted');
        }
        if (next.done) break;
        stillAlive();
        size += next.value.byteLength;
        if (size > maxBytes) {
          controller.abort();
          await reader.cancel().catch(() => undefined);
          throw new DomainValidationError(MSG_EXPORT_TOO_LARGE);
        }
        if (!file.write(next.value)) await once(file, 'drain');
      }
    }
    file.end();
    await finished(file);
    out = null;
    return size;
  } catch (error) {
    if (out) {
      out.destroy();
      await finished(out).catch(() => undefined);
    }
    await unlink(filePath).catch(() => undefined);
    throw error;
  } finally {
    clearTimeout(total);
    clearTimeout(idle);
  }
}

/**
 * Export links are single use, so the file a preview downloaded is kept for the import that
 * follows it (and for a retry after a wrong password), one per workspace and user. It is deleted
 * when forgotten (after a successful import), replaced, or 30 minutes after it was downloaded.
 */
const RECENT_TTL_MS = 30 * 60 * 1000;
const recent = new Map<string, { url: string; filePath: string; timer: NodeJS.Timeout }>();

export function recallExportDownload(key: string, url: string): string | null {
  const entry = recent.get(key);
  return entry && entry.url === url ? entry.filePath : null;
}

export function rememberExportDownload(key: string, url: string, filePath: string, ttlMs = RECENT_TTL_MS): void {
  forgetExportDownload(key);
  const timer = setTimeout(() => {
    if (recent.get(key)?.filePath === filePath) forgetExportDownload(key);
  }, ttlMs);
  timer.unref();
  recent.set(key, { url, filePath, timer });
}

export function forgetExportDownload(key: string): void {
  const entry = recent.get(key);
  if (!entry) return;
  recent.delete(key);
  clearTimeout(entry.timer);
  void unlink(entry.filePath).catch(() => undefined);
}
