import { WorkspaceRole } from './enums/workspace-role.enum';

export const PERMISSIONS = {
  // Workspace
  WORKSPACE_CREATE: 'workspace.create',
  WORKSPACE_MEMBERS_MANAGE: 'workspace.members.manage',
  WORKSPACE_INVITATIONS_MANAGE: 'workspace.invitations.manage',
  WORKSPACE_MEMBERS_VIEW: 'workspace.members.view',
  WORKSPACE_SETTINGS_MANAGE: 'workspace.settings.manage',

  // Tags
  TAG_CREATE: 'tag.create',
  TAG_DELETE: 'tag.delete',
  TAG_VIEW: 'tag.view',

  // Tickets
  TICKET_CREATE: 'ticket.create',
  TICKET_VIEW: 'ticket.view',
  TICKET_VIEW_OWN: 'ticket.view.own',
  TICKET_EDIT_NAME: 'ticket.edit.name',
  TICKET_EDIT_DESCRIPTION: 'ticket.edit.description',
  TICKET_EDIT_PRIORITY: 'ticket.edit.priority',
  TICKET_EDIT_CATEGORY: 'ticket.edit.category',
  TICKET_EDIT_TAGS: 'ticket.edit.tags',
  TICKET_CHANGE_STATUS: 'ticket.change.status',
  TICKET_CHANGE_STATUS_DISCARDED: 'ticket.change.status.discarded',
  TICKET_ASSIGN: 'ticket.assign',
  TICKET_PICKUP: 'ticket.pickup',
  TICKET_TRANSFER: 'ticket.transfer',
  TRANSFER_REQUEST_RESPOND: 'transfer-request.respond',
  TICKET_DELETE: 'ticket.delete',
  TICKET_EDIT_DISCARDED: 'ticket.edit.discarded',

  // Comments
  COMMENT_CREATE: 'comment.create',

  // Attachments
  ATTACHMENT_UPLOAD: 'attachment.upload',
  ATTACHMENT_DELETE: 'attachment.delete',

  // Users
  USER_CREATE: 'user.create',
  USER_LIST: 'user.list',

  // Canned Responses
  CANNED_RESPONSE_CREATE: 'canned-response.create',
  CANNED_RESPONSE_EDIT: 'canned-response.edit',
  CANNED_RESPONSE_DELETE: 'canned-response.delete',
  CANNED_RESPONSE_VIEW: 'canned-response.view',

  // Custom Fields
  CUSTOM_FIELD_MANAGE: 'custom-field.manage',
  CUSTOM_FIELD_VIEW: 'custom-field.view',

  // Reports
  REPORT_VIEW: 'report.view',

  // Audit Log
  AUDIT_LOG_VIEW: 'audit-log.view',

  // Departments
  DEPARTMENT_MANAGE: 'department.manage',
  DEPARTMENT_VIEW: 'department.view',

  // Organizations
  ORGANIZATION_MANAGE: 'organization.manage',
  ORGANIZATION_VIEW: 'organization.view',

  // Projects
  PROJECT_MANAGE: 'project.manage',
  PROJECT_VIEW: 'project.view',

  // Knowledge Base
  KB_ARTICLE_CREATE: 'kb.article.create',
  KB_ARTICLE_EDIT: 'kb.article.edit',
  KB_ARTICLE_DELETE: 'kb.article.delete',
  KB_ARTICLE_VIEW: 'kb.article.view',
  KB_CATEGORY_MANAGE: 'kb.category.manage',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

const ADMIN_PERMISSIONS: Permission[] = Object.values(PERMISSIONS);

const SUPERVISOR_PERMISSIONS: Permission[] = [
  PERMISSIONS.WORKSPACE_MEMBERS_VIEW,
  PERMISSIONS.WORKSPACE_INVITATIONS_MANAGE,
  PERMISSIONS.TAG_CREATE,
  PERMISSIONS.TAG_DELETE,
  PERMISSIONS.TAG_VIEW,
  PERMISSIONS.DEPARTMENT_MANAGE,
  PERMISSIONS.DEPARTMENT_VIEW,
  PERMISSIONS.ORGANIZATION_MANAGE,
  PERMISSIONS.ORGANIZATION_VIEW,
  PERMISSIONS.PROJECT_MANAGE,
  PERMISSIONS.PROJECT_VIEW,
  PERMISSIONS.TICKET_CREATE,
  PERMISSIONS.TICKET_VIEW,
  PERMISSIONS.TICKET_EDIT_NAME,
  PERMISSIONS.TICKET_EDIT_DESCRIPTION,
  PERMISSIONS.TICKET_EDIT_PRIORITY,
  PERMISSIONS.TICKET_EDIT_CATEGORY,
  PERMISSIONS.TICKET_EDIT_TAGS,
  PERMISSIONS.TICKET_CHANGE_STATUS,
  PERMISSIONS.TICKET_CHANGE_STATUS_DISCARDED,
  PERMISSIONS.TICKET_ASSIGN,
  PERMISSIONS.TICKET_PICKUP,
  PERMISSIONS.TICKET_TRANSFER,
  PERMISSIONS.TRANSFER_REQUEST_RESPOND,
  PERMISSIONS.TICKET_DELETE,
  PERMISSIONS.TICKET_EDIT_DISCARDED,
  PERMISSIONS.COMMENT_CREATE,
  PERMISSIONS.ATTACHMENT_UPLOAD,
  PERMISSIONS.ATTACHMENT_DELETE,
  PERMISSIONS.USER_LIST,
  PERMISSIONS.CANNED_RESPONSE_CREATE,
  PERMISSIONS.CANNED_RESPONSE_EDIT,
  PERMISSIONS.CANNED_RESPONSE_DELETE,
  PERMISSIONS.CANNED_RESPONSE_VIEW,
  PERMISSIONS.CUSTOM_FIELD_VIEW,
  PERMISSIONS.REPORT_VIEW,
  PERMISSIONS.KB_ARTICLE_CREATE,
  PERMISSIONS.KB_ARTICLE_EDIT,
  PERMISSIONS.KB_ARTICLE_DELETE,
  PERMISSIONS.KB_ARTICLE_VIEW,
  PERMISSIONS.KB_CATEGORY_MANAGE,
];

const AGENT_PERMISSIONS: Permission[] = [
  PERMISSIONS.TICKET_CREATE,
  PERMISSIONS.TICKET_VIEW_OWN,
  PERMISSIONS.TICKET_EDIT_DESCRIPTION,
  PERMISSIONS.TICKET_EDIT_PRIORITY,
  PERMISSIONS.TICKET_EDIT_CATEGORY,
  PERMISSIONS.TICKET_EDIT_TAGS,
  PERMISSIONS.TICKET_CHANGE_STATUS,
  PERMISSIONS.TICKET_PICKUP,
  PERMISSIONS.TICKET_TRANSFER,
  PERMISSIONS.TRANSFER_REQUEST_RESPOND,
  PERMISSIONS.TICKET_DELETE,
  PERMISSIONS.COMMENT_CREATE,
  PERMISSIONS.ATTACHMENT_UPLOAD,
  PERMISSIONS.ATTACHMENT_DELETE,
  PERMISSIONS.USER_LIST,
  PERMISSIONS.CANNED_RESPONSE_CREATE,
  PERMISSIONS.CANNED_RESPONSE_EDIT,
  PERMISSIONS.CANNED_RESPONSE_DELETE,
  PERMISSIONS.CANNED_RESPONSE_VIEW,
  PERMISSIONS.CUSTOM_FIELD_VIEW,
  PERMISSIONS.WORKSPACE_MEMBERS_VIEW,
  PERMISSIONS.KB_ARTICLE_VIEW,
  PERMISSIONS.DEPARTMENT_VIEW,
  PERMISSIONS.ORGANIZATION_VIEW,
  PERMISSIONS.PROJECT_VIEW,
];

const REPORTER_PERMISSIONS: Permission[] = [
  PERMISSIONS.TICKET_CREATE,
  PERMISSIONS.TICKET_VIEW_OWN,
  PERMISSIONS.COMMENT_CREATE,
  PERMISSIONS.ATTACHMENT_UPLOAD,
  PERMISSIONS.ATTACHMENT_DELETE,
  PERMISSIONS.USER_LIST,
  PERMISSIONS.CUSTOM_FIELD_VIEW,
];

const ROLE_PERMISSIONS: Record<WorkspaceRole, Permission[]> = {
  [WorkspaceRole.ADMIN]: ADMIN_PERMISSIONS,
  [WorkspaceRole.SUPERVISOR]: SUPERVISOR_PERMISSIONS,
  [WorkspaceRole.AGENT]: AGENT_PERMISSIONS,
  [WorkspaceRole.REPORTER]: REPORTER_PERMISSIONS,
};

export function hasPermission(role: WorkspaceRole, permission: Permission): boolean {
  return ROLE_PERMISSIONS[role].includes(permission);
}

export function getPermissionsForRole(role: WorkspaceRole): Permission[] {
  return ROLE_PERMISSIONS[role];
}
